version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  signal_mock:
    build: 
      context: .
      dockerfile: signal_mock/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    command: python main.py

  solution:
    build: 
      context: .
      dockerfile: solution/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ALPACA_API_KEY=PKB52CPUW65K5RCIOPH5
      - ALPACA_SECRET_KEY=fZj22bf2hKWbyikJjPGGCIlScMzi707gbeaRqwAw
      - ALPACA_BASE_URL=https://paper-api.alpaca.markets/v2
    depends_on:
      redis:
        condition: service_healthy
    command: python main.py